"""
영웅별 외부 가이드 링크 매핑.
출처: 디시인사이드 에픽세븐 마이너 갤러리 "이새끼템 어케 맞춤? 모음집"
https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2468784
"""

# {file1 base_name_ko: [{title, url}]}
HERO_GUIDES: dict[str, list[dict]] = {
    "고독한 늑대 페이라": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2316561"}],
    "고양이 클라릿사": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=apple1004ga&no=1818136&search_head=10&page=2"}],
    "기원의 라스": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2463338"}],
    "노토스": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2551046"}],
    "도시의 그림자 슈": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2316230"}],
    "디에네": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2318036"}],
    "뒤틀린 망령 카일론": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2475175"}],
    "라이아": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2050463"}],
    "라비": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2206716"}],
    "로앤나": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=apple1004ga&no=1720619"}],
    "리나크": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2377539"}],
    "마신의 그림자": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2317797"}],
    "모르트": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2249106"}],
    "모험가 라스": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=apple1004ga&no=1817883"}],
    "메이드 클로에": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2465395"}],
    "방관자 화영": [{"title": "디시 가이드", "url": "https://m.dcinside.com/board/epicseven/2318046"}],
    "보건교사 율하": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2498236"}],
    "보검의 군주 이세리아": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2522171"}],
    "빛의 루엘": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2474624"}],
    "베로니카": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/m/epicseven/2316277"}],
    "벨리안": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2479613"}],
    "사자왕 체르미아": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2468705"}],
    "살로메": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2606339"}],
    "설화": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2466360"}],
    "소악마 루아": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2377672"}],
    "신월의 루나": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2577013"}],
    "심연의 유피네": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2057405"}],
    "아람": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2495420"}],
    "알베도": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/m/epicseven/2316253"}],
    "어둠의 목자 디에네": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2509639"}],
    "어린 셰나": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/m/epicseven/2316273"}],
    "율하": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=1900169"}],
    "영안의 셀린": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2377290"}],
    "일편고월 벨로나": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2547365"}],
    "전술형 콜리": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2558669"}],
    "전승의 아미키": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2377521"}],
    "조장 아룬카": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2350723"}],
    "조향사 비브리스": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2572197"}],
    "집행관 빌트레드": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2168799"}],
    "천칭의 주인": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2578136"}],
    "창공의 일리나브": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2182704"}],
    "축제의 에다": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2485808"}],
    "키리스": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=apple1004ga&no=1749794"}],
    "쾌속의 기수 세크레트": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2488439"}],
    "타라노르 근위부대원": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=apple1004ga&no=1841845"}],
    "타마린느": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=apple1004ga&no=1719138"}],
    "토라미": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2558653"}],
    "풍기위원 아리아": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2381792"}],
    "프리렌": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2463215"}],
    "하르세티": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2364890"}],
    "화란의 라비": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2489048"}],
    "한낮의 유영 플랑": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2316247"}],
    "혈검 카린": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2194291"}],
    "호반의 마녀 테네브리아": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2390650"}],
    "호위대장 크라우": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2375359"}],
    "헤카테": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2585318"}],
    "해변의 벨로나": [{"title": "디시 가이드", "url": "https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2358423"}],
    # 가이드 모음 출처 (메타)
    # https://gall.dcinside.com/mgallery/board/view/?id=epicseven&no=2468784
}
